# Introduction

---
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/davidrajm/DSA-DL-FDP/blob/main/Day%2005%20-%20CNN%20-%20%20Dr%20Saraswathi/SAS_VAC_ex1.ipynb
)

In [ ]:
import numpy as np

In [ ]:
# Step 1: Dataset
X = np.array([
    [45, 0.80, 9120],
    [40, 0.12, 2000],
    [38, 0.08, 3042],
    [25, 0.03, 3300],
    [49, 0.02, 63588],
    [74, 0.37, 3500]
])

In [ ]:
X

array([[4.5000e+01, 8.0000e-01, 9.1200e+03],
       [4.0000e+01, 1.2000e-01, 2.0000e+03],
       [3.8000e+01, 8.0000e-02, 3.0420e+03],
       [2.5000e+01, 3.0000e-02, 3.3000e+03],
       [4.9000e+01, 2.0000e-02, 6.3588e+04],
       [7.4000e+01, 3.7000e-01, 3.5000e+03]])

In [ ]:
import pandas as pd

df = pd.DataFrame(X, columns=["Age", "Debt", "Income"])
df.index += 1

print(df)

    Age  Debt   Income
1  45.0  0.80   9120.0
2  40.0  0.12   2000.0
3  38.0  0.08   3042.0
4  25.0  0.03   3300.0
5  49.0  0.02  63588.0
6  74.0  0.37   3500.0


In [ ]:
y = np.array([1, 1, 0, 0, 0, 1])

In [ ]:
y

array([1, 1, 0, 0, 0, 1])

In [ ]:
# Normalize
X = X / np.max(X, axis=0)

In [ ]:
X

array([[0.60810811, 1.        , 0.14342329],
       [0.54054054, 0.15      , 0.03145248],
       [0.51351351, 0.1       , 0.04783921],
       [0.33783784, 0.0375    , 0.05189658],
       [0.66216216, 0.025     , 1.        ],
       [1.        , 0.4625    , 0.05504183]])

In [ ]:
# Initialize weights manually
weights = np.array([0.5, 0.5, 0.5])
bias = 0.1

In [ ]:
# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Forward pass
for i in range(len(X)):
    z = np.dot(X[i], weights) + bias
    pred = sigmoid(z)
    print(f"Input: {X[i]} → Prediction: {pred:.2f}")

Input: [0.60810811 1.         0.14342329] → Prediction: 0.73
Input: [0.54054054 0.15       0.03145248] → Prediction: 0.61
Input: [0.51351351 0.1        0.04783921] → Prediction: 0.61
Input: [0.33783784 0.0375     0.05189658] → Prediction: 0.58
Input: [0.66216216 0.025      1.        ] → Prediction: 0.72
Input: [1.         0.4625     0.05504183] → Prediction: 0.70


In [ ]:
#option 2

import numpy as np
import pandas as pd

# Step 1: Dataset
X = np.array([
    [45, 0.80, 9120],
    [40, 0.12, 2000],
    [38, 0.08, 3042],
    [25, 0.03, 3300],
    [49, 0.02, 63588],
    [74, 0.37, 3500]
])

# Actual values (Column W)
y = np.array([1, 1, 0, 0, 0, 0])

# Step 2: Normalize
X_norm = X / np.max(X, axis=0)

# Step 3: Manual weights (to get mixed predictions)
weights = np.array([0.2, 3.0, -2.5])
bias = -0.5

# Step 4: Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Step 5: Predictions
predictions = []
errors = []

for i in range(len(X_norm)):
    z = np.dot(X_norm[i], weights) + bias
    pred = sigmoid(z)
    predictions.append(round(pred, 2))
    errors.append(round(y[i] - pred, 2))  # same as your table

# Step 6: Create DataFrame
df = pd.DataFrame({
    "Customer ID": range(1, 7),
    "Customer Age": X[:, 0],
    "Debt Ratio": X[:, 1],
    "Monthly Income": X[:, 2],
    "Loan Defaulter (W)": y,
    "Default Prediction (X)": predictions,
    "Prediction Error": errors
})

# Step 7: Print nicely
print(df)

   Customer ID  Customer Age  Debt Ratio  Monthly Income  Loan Defaulter (W)  \
0            1          45.0        0.80          9120.0                   1   
1            2          40.0        0.12          2000.0                   1   
2            3          38.0        0.08          3042.0                   0   
3            4          25.0        0.03          3300.0                   0   
4            5          49.0        0.02         63588.0                   0   
5            6          74.0        0.37          3500.0                   0   

   Default Prediction (X)  Prediction Error  
0                    0.91              0.09  
1                    0.49              0.51  
2                    0.45             -0.45  
3                    0.39             -0.39  
4                    0.06             -0.06  
5                    0.72             -0.72  


In [ ]:
def highlight(val):
    if val > 0:
        return 'color: green'
    else:
        return 'color: red'

df.style.applymap(highlight, subset=["Prediction Error"])

/tmp/ipykernel_12136/3447464524.py:7: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(highlight, subset=["Prediction Error"])


,Customer ID,Customer Age,Debt Ratio,Monthly Income,Loan Defaulter (W),Default Prediction (X),Prediction Error
0,1,45.000000,0.800000,9120.000000,1,0.910000,0.090000
1,2,40.000000,0.120000,2000.000000,1,0.490000,0.510000
2,3,38.000000,0.080000,3042.000000,0,0.450000,-0.450000
3,4,25.000000,0.030000,3300.000000,0,0.390000,-0.390000
4,5,49.000000,0.020000,63588.000000,0,0.060000,-0.060000
5,6,74.000000,0.370000,3500.000000,0,0.720000,-0.720000


In [ ]:
# MLP

import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Step 1: Dataset
X = np.array([
    [45, 0.80, 9120],
    [40, 0.12, 2000],
    [38, 0.08, 3042],
    [25, 0.03, 3300],
    [49, 0.02, 63588],
    [74, 0.37, 3500]
])

y = np.array([1, 1, 0, 0, 0, 0])

# Step 2: Normalize
X = X / np.max(X, axis=0)

# -------------------------------
# 🔷 MODEL 1: SINGLE LAYER
# -------------------------------
model1 = Sequential([
    Dense(1, input_dim=3, activation='sigmoid')
])

model1.compile(optimizer='adam', loss='binary_crossentropy')
model1.fit(X, y, epochs=100, verbose=0)

pred1 = model1.predict(X).flatten()

# -------------------------------
# 🔷 MODEL 2: MLP
# -------------------------------
model2 = Sequential([
    Dense(4, input_dim=3, activation='relu'),  # hidden layer
    Dense(1, activation='sigmoid')
])

model2.compile(optimizer='adam', loss='binary_crossentropy')
model2.fit(X, y, epochs=100, verbose=0)

pred2 = model2.predict(X).flatten()

# -------------------------------
# 🔷 CREATE COMPARISON TABLE
# -------------------------------
df = pd.DataFrame({
    "Customer ID": range(1, 7),
    "Actual": y,
    "Single Layer Output": np.round(pred1, 2),
    "MLP Output": np.round(pred2, 2)
})

print(df)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
   Customer ID  Actual  Single Layer Output  MLP Output
0            1       1                 0.72        0.57
1            2       1                 0.57        0.48
2            3       0                 0.55        0.48
3            4       0                 0.51        0.48
4            5       0                 0.32        0.46
5            6       0                 0.68        0.48


In [ ]:
df["Single Layer Class"] = df["Single Layer Output"].apply(lambda x: 1 if x > 0.5 else 0)
df["MLP Class"] = df["MLP Output"].apply(lambda x: 1 if x > 0.5 else 0)

print(df)

   Customer ID  Actual  Single Layer Output  MLP Output  Single Layer Class  \
0            1       1                 0.72        0.57                   1   
1            2       1                 0.57        0.48                   1   
2            3       0                 0.55        0.48                   1   
3            4       0                 0.51        0.48                   1   
4            5       0                 0.32        0.46                   0   
5            6       0                 0.68        0.48                   1   

   MLP Class  
0          1  
1          0  
2          0  
3          0  
4          0  
5          0  
